// DO NOT EDIT THIS FILE!!! IT WILL BE AUTOMATICALLY GENERATED FROM src/i18n
/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Noolite adapter settings": {"en": "Noolite adapter settings",  "de": "Noolite adapter settings",   "ru": "Noolite adapter settings"},
    "PR1132 Gateway IP:":       {"en": "PR1132 Gateway IP",         "de": "PR1132 Gateway IP",          "ru": "PR1132 Gateway IP"},
    "Update interval:":         {"en": "Update interval",           "de": "Update interval",            "ru": "Update interval"},
    "ms":                       {"en": "ms",                        "de": "ms",                         "ru": "ms"},
    "Ch":                       {"en": "Ch",                        "de": "Ch",                         "ru": "Ch"},
    "Active":                   {"en": "Active",                    "de": "Active",                     "ru": "Active"},
    "Name":                     {"en": "Name",                      "de": "Name",                       "ru": "Name"},
    "Type":                     {"en": "Type",                      "de": "Type",                       "ru": "Type"},
    "Connect":                  {"en": "Pairing",                   "de": "Paarbildung",                "ru": "При/от-вязка"},
    "on/off":                   {"en": "on/off",                    "de": "An/Aus",                     "ru": "вкл./выкл."},
    "dimmer":                   {"en": "dimmer",                    "de": "Dimmer",                     "ru": "Диммирование"},
    "rgb":                      {"en": "RGB",                       "de": "RGB",                        "ru": "RGB контроллер"},
    "seconds":                  {"en": "seconds",                   "de": "seconds",                    "ru": "seconds"},
    "Pair device to channel":   {"en": "Pair device to channel",    "de": "Pair device to channel",     "ru": "Pair device to channel"},
    "TX USB Type:":             {"en": "TX USB Type",               "de": "TX USB Typ",                 "ru": "TX USB тип"},
    "RX USB Type:":             {"en": "RX USB Type",               "de": "RX USB Typ",                 "ru": "RX USB тип"},
    "Windows exe:":             {"en": "Windows EXE",               "de": "Windows EXE",                "ru": "Windows exe"},
    "Channel number": {
        "en": "Channel number",
        "de": "Kanal Nummer",
        "ru": "Номер канала",
        "pt": "Número do canal",
        "nl": "Kanaal nummer",
        "fr": "Le numéro de canal",
        "it": "Numero del canale",
        "es": "Numero de canal",
        "pl": "Numer kanału",
        "zh-cn": "频道号"
    },
    "Common settings": {
        "en": "Common settings",
        "de": "Allgemeine Einstellungen",
        "ru": "Общие настройки",
        "pt": "Configurações padrão",
        "nl": "Veelvoorkomende instellingen",
        "fr": "Paramètres communs",
        "it": "Impostazioni comuni",
        "es": "Configuraciones comunes",
        "pl": "Wspólne ustawienia",
        "zh-cn": "常用设定"
    },
    "Channels": {
        "en": "Channels",
        "de": "Kanäle",
        "ru": "каналы",
        "pt": "Canais",
        "nl": "kanalen",
        "fr": "Chaînes",
        "it": "canali",
        "es": "Canales",
        "pl": "Kanały",
        "zh-cn": "频道"
    }
};
